# Generated by Django 2.2.1 on 2019-06-21 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('title', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_type', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(null=True)),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='title.Book')),
                ('transaction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='transaction.Master')),
            ],
            options={
                'permissions': (('can_mark_returned', 'Set book as returned'), ('can_mark_hiring', 'Set book as hiring'), ('can_reject_hiring', 'Reject as hiring'), ('can_create_transaction', 'Create new transaction'), ('can_view_all_transactions', 'View all transaction')),
            },
        ),
    ]
