# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20181118_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.master'),
        ),
    ]
