# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_detail_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('can_mark_hiring', 'Set book as hiring'))},
        ),
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
