# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20181231_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('can_mark_hiring', 'Set book as hiring'), ('can_reject_hiring', 'Reject as hiring'))},
        ),
    ]
