# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190106_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('can_mark_hiring', 'Set book as hiring'), ('can_reject_hiring', 'Reject as hiring'), ('can_create_transaction', 'Create new transaction'), ('can_view_all_transactions', 'View all transaction'))},
        ),
    ]
