# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20190106_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Book'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='detail',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.Master'),
        ),
    ]
