# Generated by Django 2.2.1 on 2019-05-21 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190428_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='title.Book'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='transaction.Master'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
