# Generated by Django 2.2.1 on 2019-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title_id', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rating_timestamp', models.DateTimeField()),
                ('type', models.CharField(default='calculate', max_length=10)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
