# Generated by Django 2.2.1 on 2019-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.CharField(default='calculate', max_length=20),
        ),
    ]
