# Generated by Django 2.2.1 on 2019-07-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20190721_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title'),
        ),
    ]
