# Generated by Django 2.2.1 on 2019-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20190725_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='target',
            field=models.IntegerField(),
        ),
    ]
