# Generated by Django 2.2.1 on 2019-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20190727_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatingSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('source', models.IntegerField(db_index=True)),
                ('target', models.IntegerField()),
                ('similarity', models.DecimalField(decimal_places=7, max_digits=8)),
            ],
            options={
                'db_table': 'user_rating_similarity',
            },
        ),
        migrations.RenameModel(
            old_name='UserSimilarity',
            new_name='ItemRatingSimilarity',
        ),
        migrations.AlterModelTable(
            name='itemratingsimilarity',
            table='item_rating_similarity',
        ),
    ]
