# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('faculty', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(max_length=5)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(default=0)),
                ('week_price', models.FloatField(default=0)),
                ('sem_price', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('ori_quantity', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='title.Author')),
                ('publisher', models.ManyToManyField(to='title.Publisher')),
            ],
        ),
    ]
