# Generated by Django 2.2.1 on 2019-06-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('faculty', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(max_length=5)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('topic', models.CharField(default='', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('week_price', models.FloatField(default=0)),
                ('sem_price', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('ori_quantity', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='title.Author')),
                ('publisher', models.ManyToManyField(to='title.Publisher')),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('barcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='title.Title')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
