# Generated by Django 2.2.1 on 2019-07-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'permissions': (('login_dashboard', 'Login to dashboard'),)},
        ),
    ]
