# Generated by Django 2.2.1 on 2019-07-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20190714_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
