# Generated by Django 2.2.1 on 2019-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_auto_20190522_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='topic',
            field=models.CharField(default='', max_length=512),
        ),
    ]
