# Generated by Django 2.2.1 on 2019-07-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_auto_20190714_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='topic',
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
